database:
  default: {database_default}
  providers:
    - name: mysql
      hostname: {mysql_hostname}
      username: {mysql_password}

    - name: postgres
      hostname: {postgres_hostname}
      username: {postgres_password}

persistence:
  amazon:
      bucket: {amazon_bucket}
  azure:
      storage: {azure_storage}
  local:
      directory: {local_directory}


crypto:
  magical_numbers: [1,3,5,7]
  best_algorithm: caesar



queue:
   max_instances: {queue_max_instances}
   workers:
      - name: cpu_intensive
        scheduler_plans:
            low: [1, 3, 5, 7]
            high: [10]
      - name: video_encoding
        scheduler_plans:
            low: [1]
            high: [2, 4, 6, 8]


